name: trafo_rapor
description: Trafo Bakım ve Kontrol Raporlama Uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # PDF
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  
  # Fotoğraf
  image_picker: ^1.0.7
  
  # Paylaşım
  share_plus: ^7.2.2
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
